use std::fs;
use std::fs::File;
use std::fs::OpenOptions;
use std::io::Read;
use std::path::Path;
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

use simple_config_parser::config;
use tar;

use crate::VERSION;

#[derive(Debug, Clone)]
pub struct Config {
    pub game_path: PathBuf,

    // Game Settings
    pub volume: u8,
    pub full_screen: bool,
}

#[derive(Debug, Clone)]
pub enum ConfigUpdate {
    Volume(u8),
    FullScreen(bool),
    GamePath(String),
}

impl Config {
    pub fn load(path: PathBuf) -> Option<Config> {
        let mut file = OpenOptions::new().read(true).open(path).ok()?;
        let mut data = String::new();
        file.read_to_string(&mut data).ok()?;

        let mut cfg = config::Config::new(None);
        cfg.parse(&data.replace('\r', "")).ok()?;

        let game_path = cfg.get("game_path")?;

        let game_config = fs::read_to_string(Path::new(&game_path).join("freeways.cfg")).ok()?;

        let mut game_config_data = game_config.split('"');

        Some(Config {
            game_path: Path::new(&game_path).to_path_buf(),
            volume: game_config_data.clone().nth(7).unwrap().parse().ok()?,
            full_screen: game_config_data.nth(1).unwrap() == "true",
            ..Config::default()
        })
    }

    pub fn apply_update(&self, update: ConfigUpdate) -> Config {
        match update {
            ConfigUpdate::Volume(volume) => Config {
                volume,
                ..self.clone()
            },

            ConfigUpdate::FullScreen(full_screen) => Config {
                full_screen,
                ..self.clone()
            },

            ConfigUpdate::GamePath(game_path) => Config {
                game_path: Path::new(&game_path).to_path_buf(),
                ..self.clone()
            },
        }
    }

    pub fn save(&self, path: PathBuf) -> Option<()> {
        fs::create_dir_all(path.parent().unwrap()).ok()?;

        fs::write(
            path,
            format!(
                "; Freeways-Launcher V{} Config\ngame_path = {}\n",
                VERSION,
                self.game_path.to_string_lossy()
            ),
        )
        .ok()?;

        Some(())
    }
}

impl Default for Config {
    fn default() -> Config {
        // TODO: Support for other os
        Config {
            game_path: Path::new(r#"C:\Program Files\Steam\steamapps\common\Freeways"#)
                .to_path_buf(),
            volume: 100,
            full_screen: false,
        }
    }
}

pub fn check_data_dir(path: PathBuf) -> Option<()> {
    // Make a default config file
    if !path.join("config.cfg").exists() {
        Config::default().save(path.join("config.cfg"))?;
    }

    // Make the resource_packs folder
    if !path.join("resource_packs").exists() {
        fs::create_dir(path.join("resource_packs")).ok()?;
    }

    // Add defult rescorses from game dir into a resource pack
    if !path.join("resource_packs").join("default.tar").exists() {
        let game_path = Config::load(path.join("config.cfg"))?.game_path;

        let file = File::create(path.join("resource_packs").join("default.tar")).ok()?;
        let mut a = tar::Builder::new(file);

        let data: &[u8] = "; Default Freeways Resources\n; Generated by Freeways-Launcher (https://github.com/Basicprogrammer10/Freeways-Lancher)\nname = Default\nauthor = Captain Games\nversion = 1.0\n".as_bytes();

        let mut header = tar::Header::new_gnu();
        header.set_path("pack.meta").unwrap();
        header.set_size(data.len() as u64);
        header.set_mtime(SystemTime::now().duration_since(UNIX_EPOCH).ok()?.as_secs());
        header.set_cksum();

        a.append(&header, data).unwrap();
        a.append_dir_all("assets", game_path.join("data")).ok()?;
        a.into_inner().ok()?;
    }

    Some(())
}
